name = "vibranet"
main = "src/index.ts"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "VibraNet-DB"
database_id = "vibranet-db"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "f833646baaca43d1b762d7a97f1b7e46"

[vars]
ENVIRONMENT = "production"
