name = "vibranet"
main = "src/index.ts"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "VibraNet-DB"
database_id = "edf4ba6e-c403-410c-aa50-8229c7b03388"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "f833646baaca43d1b762d7a97f1b7e46"

[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGIN = "https://vibranet.codeberg.page"

[observability]
enabled = true

[secrets]
required = [
  "JWT_SECRET",
  "TOKEN_PEPPER"
]
